#Garage
- alias: Close Garage Door after set time
  trigger:
    platform: state
    entity_id: garage_door.garage_opener
    state: 'open'
  condition: use_trigger_values
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_garage

#Locks
- alias: Lock back door after set time
  trigger:
    platform: state
    entity_id: lock.back_door__2
    state: 'unlocked'
  condition: use_trigger_values
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_backdoor

- alias: Lock front door after set time
  trigger:
    platform: state
    entity_id: lock.front_door__3
    state: 'unlocked'
  condition: use_trigger_values
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_frontdoor

- alias: Lock garage door after set time
  trigger:
    platform: state
    entity_id: lock.garage_door__4
    state: 'unlocked'
  condition: use_trigger_values
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_garagedoor

- alias: 'Battery Low Alert'
  trigger:
  - platform: numeric_state
    entity_id: sensor.batt_frontdoor
    below: 5
  - platform: numeric_state
    entity_id: sensor.batt_backdoor
    below: 5
  - platform: numeric_state
    entity_id: sensor.batt_garagedoor
    below: 5
  action:
    service: notify.pushbullet
    data:
      message: "Time to change the front door's battery"
      title: ""

- alias: Lock all doors when not home
  trigger:
    platform: state
    entity_id: group.users
    state: 'not_home'
  action:
    service: lock.lock

- alias: Thermostat - Away
  trigger:
    platform: state
    entity_id: group.users
    to: 'not_home'
  condition:
    platform: state
    entity_id: input_boolean.thermo_home_away
    state: 'off'
  action:
    service: thermostat.set_away_mode
    data:
      entity_id: thermostat.home
      away_mode: 'true'

- alias: Thermostat - Manual Away Off
  trigger:
    platform: state
    entity_id: input_boolean.thermo_away
    state: 'off'
  condition: use_trigger_values
  action:
    service: thermostat.set_away_mode
    data:
      entity_id: thermostat.home
      away_mode: 'false'

- alias: Thermostat - Manual Away On
  trigger:
    platform: state
    entity_id: input_boolean.thermo_away
    state: 'on'
  condition: use_trigger_values
  action:
    service: thermostat.set_away_mode
    data:
      entity_id: thermostat.home
      away_mode: 'true'
