#security
- alias: Panic Mode On
  trigger:
    platform: state
    entity_id: input_boolean.panic_mode
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.alarm_tripped
        
- alias: Panic Mode Off
  trigger:
    platform: state
    entity_id: input_boolean.panic_mode
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: script.all_clear

- alias: Security Garage Opener
  trigger:
    platform: state
    entity_id: garage_door.garage_opener
    state: 'open'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.security_system
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.alarm_tripped
     
- alias: Security Garage Door
  trigger:
    platform: state
    entity_id: lock.garage_door__4
    state: 'unlocked'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.security_system
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.alarm_tripped

- alias: Security Garage Door Burglar
  trigger:
    platform: template
    value_template: "{% if is_state('sensor.garage_door_burglar_4.state', '0') %}false{% endif %}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.security_system
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.alarm_tripped

- alias: Security Back Door
  trigger:
    platform: state
    entity_id: lock.back_door__2
    state: 'unlocked'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.security_system
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.alarm_tripped

- alias: Security Back Door Burglar
  trigger:
    platform: template
    value_template: "{% if is_state('sensor.back_door_burglar_2.state', '0') %}false{% endif %}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.security_system
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.alarm_tripped

- alias: Security Front Door
  trigger:
    platform: state
    entity_id: lock.front_door__3
    state: 'unlocked'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.security_system
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.alarm_tripped

- alias: Security Front Door Burglar
  trigger:
    platform: template
    value_template: "{% if is_state('sensor.front_door_burglar_3.state', '0') %}false{% endif %}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.security_system
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.alarm_tripped

- alias: Security Upstairs
  trigger:
    platform: state
    entity_id: sensor.upstairs_occupancy
    state: 'true'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.security_system
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.alarm_tripped

- alias: Security Downstairs
  trigger:
    platform: state
    entity_id: sensor.home_occupancy
    state: 'true'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.security_system
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.alarm_tripped
     
- alias: Security Laundry Room Light
  trigger:
    platform: state
    entity_id: switch.laundry_room__6
    state: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.security_system
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.alarm_tripped
     
- alias: Security Basement Window Sensor
  trigger:
    platform: state
    entity_id: binary_sensor.basement_window_sensor_sensor_5
    state: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.security_system
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.alarm_tripped

#locks
- alias: Lock All Doors
  trigger:
    platform: state
    entity_id: input_boolean.lock_all_doors
    state: 'on'
  condition: use_trigger_values
  action:
    service: lock.lock

- alias: Lock back door after set time
  trigger:
    platform: state
    entity_id: lock.back_door__2
    state: 'unlocked'
  condition:
    condition: state
    entity_id: input_boolean.auto_lock_timer
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_backdoor

- alias: Lock front door after set time
  trigger:
    platform: state
    entity_id: lock.front_door__3
    state: 'unlocked'
  condition:         
    condition: state
    entity_id: input_boolean.auto_lock_timer
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_frontdoor

- alias: Lock garage door after set time
  trigger:
    platform: state
    entity_id: lock.garage_door__4
    state: 'unlocked'
  condition:         
    condition: state
    entity_id: input_boolean.auto_lock_timer
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_garagedoor

- alias: 'Battery Low Alert'
  trigger:
      - platform: numeric_state
        entity_id: sensor.batt_frontdoor
        below: 5
      - platform: numeric_state
        entity_id: sensor.batt_backdoor
        below: 5
      - platform: numeric_state
        entity_id: sensor.batt_garagedoor
        below: 5
  condition: use_trigger_values
  action:
    service: notify.googlevoice
    data:
      message: "Time to change the front door's battery"
      target: me

- alias: Lock all doors when not home
  trigger:
    platform: state
    entity_id: group.users
    state: 'not_home'
  condition: use_trigger_values
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: input_boolean.security_system
    - service: lock.lock

#garage
- alias: Close Garage Door after set time
  trigger:  
    platform: state
    entity_id: garage_door.garage_opener
    state: 'open'
  condition:
    condition: state
    entity_id: input_boolean.garageopener_autoclose
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_garage

- alias: Unlock garage door detect phone
  trigger:
    platform: state
    entity_id: sensor.nateiphone
    state: 'home'
  condition:
    condition: state
    entity_id: input_boolean.garage_bt
    state: 'on'
  action:
    service: lock.unlock
    entity_id: lock.garage_door__4

- alias: Lock garage door no detect phone
  trigger:
    platform: state
    entity_id: sensor.nateiphone
    state: 'home'
  condition:
    condition: state
    entity_id: input_boolean.garage_bt
    state: 'on'
  action:
    service: lock.lock
    entity_id: lock.garage_door__4

- alias: Garage opener detect car
  trigger:
    platform: state
    entity_id: sensor.natecar
    state: 'home'
  condition:
    condition: state
    entity_id: input_boolean.garage_bt
    state: 'on'
  action:
    service: garage_door.open     
    entity_id: garage_door.garage_opener

- alias: Garage opener no detect car
  trigger:
    platform: state
    entity_id: sensor.natecar
    state: 'home'
  condition:
    condition: state
    entity_id: input_boolean.garage_bt
    state: 'on'
  action:
    service: garage_door.close
    entity_id: garage_door.garage_opener

#switch_lights
- alias: Turn on laundry room light when coming home
  trigger:
    - platform: state
      entity_id: device_tracker.me
      state: 'home'
    - platform: state
      entity_id: device_tracker.her
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-4:00:00'
      - condition: state
        entity_id: input_boolean.disable_light_timer
        state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_laundryroom

- alias: Turn off all indoor lights
  trigger:
    platform: state
    entity_id: group.users
    state: 'not_home'
  condition: use_trigger_values
  action:
    service: switch.turn_off
    entity_id: group.indoor_lights

#googletravel
- alias: "Commute to work by car"
  trigger:
    platform: time
    after: '7:30'
  condition:
    condition: numeric_state
    entity_id: sensor.google_travel_time_car
    below: 30
  action:
    service: notify.googlevoice
    data:
      message: "Commute by car less than 30 minutes"
      target: me

- alias: "Commute to work by bike"
  trigger:
    platform: time
    after: '6:15'
  condition:
    condition: numeric_state
    entity_id: sensor.google_travel_time_bike
    below: 50
  action:
    service: notify.googlevoice
    data:
      message: "Commute by bike less than 50 minutes"
      target: me

#thermostat
- alias: Thermostat - Auto Home
  trigger:
    platform: state
    entity_id: group.users
    state: 'home'
  condition: use_trigger_values
  action:
    service: thermostat.set_away_mode
    data:
      entity_id: thermostat.home
      away_mode: 'False'
      
- alias: Thermostat - Auto Away
  trigger:
    platform: state
    entity_id: group.users
    state: 'not_home'
  condition: use_trigger_values
  action:
    service: thermostat.set_away_mode
    data:
      entity_id: thermostat.home
      away_mode: 'True'
     
#zwave
- alias: heal at 2:30am
  trigger:
    platform: time
    after: '2:30:00'
  condition: use_trigger_values
  action:
    service: zwave.heal_network
