#garage
<<<<<<< HEAD
- alias: Close Garage Door after set time
  condition: state
  entity_id: garage_door.garage_opener
  state: 'open'
=======
- alias: Close garage door after set time
  trigger:
    platform: state
    entity_id: garage_door.garage_opener
    state: 'open'
  condition: use_trigger_values
>>>>>>> origin/master
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_garage

#locks
- alias: Lock back door after set time
  condition: state
  entity_id: lock.back_door__2
  state: 'unlocked'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_backdoor

- alias: Lock front door after set time
  condition: state
  entity_id: lock.front_door__3
  state: 'unlocked'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_frontdoor

- alias: Lock garage door after set time
  condition: state
  entity_id: lock.garage_door__4
  state: 'unlocked'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_garagedoor

- alias: 'Battery Low Alert'
  condition: or
  conditions:
  - condition: numeric_state
    entity_id: sensor.batt_frontdoor
    below: 5
  - condition: numeric_state
    entity_id: sensor.batt_backdoor
    below: 5
  - condition: numeric_state
    entity_id: sensor.batt_garagedoor
    below: 5
  action:
    service: notify.pushbullet
    data:
      message: "Time to change the front door's battery"

- alias: Lock all doors when not home
  condition: state
  entity_id: group.users
  state: 'not_home'
  action:
    service: lock.lock

<<<<<<< HEAD
#switch_lights
- alias: Turn on laundry room light when coming home
  condition: or
  conditions:
    - condition: state
      entity_id: device_tracker.me
      state: 'home'
    - condition: state
=======
#lights
- alias: Turn on laundry room light when coming home
  trigger:
    - platform: state
      entity_id: device_tracker.me
      state: 'home'
    - platform: state
>>>>>>> origin/master
      entity_id: device_tracker.her
      state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_laundryroom

<<<<<<< HEAD
- alias: Turn off all indoor lights
  condition: state
  entity_id: group.users
  state: 'not_home'
=======
- alias: Turn off indoor lights when not home
  trigger:
    platform: state
    entity_id: group.users
    to: 'not_home'
>>>>>>> origin/master
  action:
    service: switch.turn_off
    entity_id: group.indoor_lights

#googletravel
- alias: "Commute to work by car"
  condition:
    - condition: time
<<<<<<< HEAD
      after: '9:00:00'
      before: '10:00:00'
  trigger:
    platform: numeric_state
    entity_id: sensor.google_travel_time_car
    below: 30
  action:
    service: notify.pushbullet
    data:
      message: "Commute by car less than 30 minutes"

- alias: "Commute to work by bike"
  condition:
    - condition: time
      after: '6:00:00'
      before: '7:15:00'
  trigger:
    platform: numeric_state
    entity_id: sensor.google_travel_time_bike
    below: 50
  action:
    service: notify.pushbullet
    data:
      message: "Commute by bike less than 50 minutes"

#thermostat
- alias: Thermostat - Auto Home
  condition: state
  entity_id: group.users
  state: 'home'
=======
      after: '7:00:00'
      before: '8:00:00'
  trigger:
    platform: numeric_state
    entity_id: sensor.google_travel_time
    below: 30
  action:
    service: notify.pushbullet
    data:
      message: "Commute less than 30 minutes"

#thermostat
- alias: Thermostat - Auto Home
  trigger:
    platform: state
    entity_id: group.users
    state: 'home'
  condition: use_trigger_values
>>>>>>> origin/master
  action:
    service: thermostat.set_away_mode
    data:
      entity_id: thermostat.home
<<<<<<< HEAD
      away_mode: 'False'
      
- alias: Thermostat - Auto Away
  condition:
  entity_id: group.users
  state: 'not_home'
=======
      away_mode: 'off'
      
- alias: Thermostat - Auto Away
  trigger:
    platform: state
    entity_id: group.users
    state: 'not_home'
  condition: use_trigger_values
>>>>>>> origin/master
  action:
    service: thermostat.set_away_mode
    data:
      entity_id: thermostat.home
<<<<<<< HEAD
      away_mode: 'True'
=======
      away_mode: 'on'

#- alias: Thermostat - Home
#  trigger:
#    platform: state
#    entity_id: group.users
#    to: 'home'
#  condition:
#    platform: state
#    entity_id: input_boolean.thermo_home_away
#    state: 'off'
#  action:
#    service: thermostat.set_away_mode
#    data:
#      entity_id: thermostat.home
#      away_mode: 'false'

#- alias: Thermostat - Away
#  trigger:
#    platform: state
#    entity_id: group.users
#    to: 'not_home'
#  condition:
#    platform: state
#    entity_id: input_boolean.thermo_home_away
#    state: 'off'
#  action:
#    service: thermostat.set_away_mode
#    data:
#      entity_id: thermostat.home
#      away_mode: 'true'

#- alias: Thermostat - Manual Away Off
#  trigger:
#    platform: state
#    entity_id: input_boolean.thermo_away
#    state: 'off'
#  condition: use_trigger_values
#  action:
#    service: thermostat.set_away_mode
#    data:
#      entity_id: thermostat.home
#      away_mode: 'false'

#- alias: Thermostat - Manual Away On
#  trigger:
#    platform: state
#    entity_id: input_boolean.thermo_away
#    state: 'on'
#  condition: use_trigger_values
#  action:
#    service: thermostat.set_away_mode
#    data:
#      entity_id: thermostat.home
#      away_mode: 'true'

#zwave
- alias: heal at 2:30am
  trigger:
    platform: time
    after: '2:30:00'
  action:
    service: zwave.heal_network
>>>>>>> origin/master
