- platform: nmap_tracker
  hosts: !env_var NETBLOCK
  consider_home: 300
  home_interval: 45
  
- platform: icloud
  username: !env_var MYICLOUDU
  password: !env_var MYICLOUDP
  track_new_devices: no
  interval: 900

- platform: icloud
  username: !env_var HERICLOUDU
  password: !env_var HERICLOUDP
  interval: 900
  
#- platform: bluetooth_tracker
