- name: myiphone
  platform: ios
  target: '[redacted]'

- name: heriphone
  platform: ios
  target: '[redacted]'

- platform: googlevoice
  username: !env_var GVUSER
  password: !env_var GVPASS
  name: googlevoice
