#locks
- platform: template
  sensors:
    front_door_batt:
      value_template: '{{ states.lock.front_door__3.attributes.battery_level }}'
      unit_of_measurement: '%'

- platform: template
  sensors:
    back_door_batt:
      value_template: '{{ states.lock.back_door__2.attributes.battery_level }}'
      unit_of_measurement: '%'

- platform: template
  sensors:
    garage_door_batt:
      value_template: '{{ states.lock.garage_door__4.attributes.battery_level }}'
      unit_of_measurement: '%'

#garage
- platform: template
  sensors:
    garageopener_status:
      value_template: '{{ states.garage_door.garage_opener.state }}'

- platform: template
  sensors:
    garage_camera:
      value_template: '{{ states.camera.garage.state }}'

#thermostat
- platform: template
  sensors:
    thermostat_mode:
      value_template: '{{ states.thermostat.home.attributes.mode }}'

- platform: template
  sensors:
    thermostat_away:
      value_template: '{{ states.thermostat.home.attributes.away_mode }}'

- platform: template
  sensors:
    thermostat_hvac:
      value_template: '{{ states.thermostat.home.attributes.hvac_mode }}'

- platform: template
  sensors:
    thermostat_target_temp_low:
      value_template: '{{ states.thermostat.home.attributes.target_temp_low }}'

- platform: template
  sensors:
    thermostat_target_temp_high:
      value_template: '{{ states.thermostat.home.attributes.target_temp_high }}'

#googletravel
- platform: google_travel_time
  name: 'google_travel_time_car'
  api_key: !env_var GOOGLE_API
  origin: !env_var HOME_LATITUDE , !env_var HOME_LONGITUDE
  destination: !env_var WORK_LAT , !env_var WORK_LONG
  options:
    arrival_time: 08:00:00
    mode: driving

- platform: template
  sensors:
    google_travel_car_time:
      value_template: '{{ states.sensor.google_travel_time_car.attributes.duration }}'

- platform: google_travel_time
  name: 'google_travel_time_bike'
  api_key: !env_var GOOGLE_API
  origin: !env_var HOME_LATITUDE , !env_var HOME_LONGITUDE
  destination: !env_var WORK_LAT , !env_var WORK_LONG
  options:
    mode: bicycling
    

- platform: template
  sensors:
    google_travel_bike_time:
      value_template: '{{ states.sensor.google_travel_time_bike.attributes.duration }}'

speedtest
- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

#weather
- platform: forecast
  api_key: !env_var FORECAST_API
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone

#system
- platform: glances
  name: System Stats
  host: 127.0.0.1
  port: 61208
  resources:
    - 'disk_use_percent'
    - 'disk_use'
    - 'disk_free'
    - 'memory_use_percent'
    - 'memory_use'
    - 'memory_free'
    - 'swap_use_percent'
    - 'swap_use'
    - 'swap_free'
    - 'processor_load'
    - 'process_running'
    - 'process_total'
    - 'process_thread'
    - 'process_sleeping'

#sabnzbd
- platform: sabnzbd
  name: SABnzbd
  api_key: !env_var SABNZBD_KEY
  base_url: http://!env_var SABNZBD_HOST
  monitored_variables:
    - type: 'current_status'
    - type: 'speed'
    - type: 'queue_size'
    - type: 'queue_remaining'
    - type: 'disk_size'
    - type: 'disk_free'
