- alias: Alarm Triggers
  trigger:
      #garagedooropener
    - platform: state
      entity_id: garage_door.garage_opener
      state: 'open'
      #garagedoorlock
    - platform: state
      entity_id: !env_var GARAGEDOORLOCK
      state: 'unlocked'
      #garagedoorlock burglar
    - platform: state
      entity_id: !env_var GDB
      state: '2'
      #garagedoorlock tamper
    - platform: state
      entity_id: !env_var GDAT
      state: '161'
      #backdoorlock
    - platform: state
      entity_id: !env_var BACKDOORLOCK
      state: 'unlocked'
      #backdoorlock burglar
    - platform: state
      entity_id: !env_var BDB
      state: '2'
      #backdoorlock tamper
    - platform: state
      entity_id: !env_var BDAT
      state: '161'
      #frontdoorlock
    - platform: state
      entity_id: !env_var FRONTDOORLOCK
      state: 'unlocked'
      #frontdoorlock burglar
    - platform: state
      entity_id: !env_var FDB
      state: '2'
      #frontdoorlock tamper
    - platform: state
      entity_id: !env_var FDAT
      state: '161'  
      #upstairs occupancy
    - platform: state
      entity_id: !env_var THERMOEXTOC
      from: 'false'
      to: 'true'
      #downstairs occupancy
    - platform: state
      entity_id: !env_var THERMOOC
      from: 'false'
      to: 'true'
      #indoor lights
    - platform: state
      entity_id: group.indoor_lights
      from: 'off'
      to: 'on'
      #basementwindow sensor
    - platform: state
      entity_id: !env_var BASEMENTWINDOW
      from: 'off'
      to: 'on'
  condition:
      condition: state
      entity_id: input_boolean.security_system
      state: 'on'
  action:
    service: script.alarm_tripped
