- alias: Alarm Home Triggers
  trigger:
      #garagedoorunlockedmanually
    - platform: state
      entity_id: !env_var GDAT
      state: '22'
      #garagedooropener
    - platform: state
      entity_id: garage_door.garage_opener
      from: 'closed'
      to: 'open'
      #garagedoorlock burglar
    - platform: state
      entity_id: !env_var GDB
      state: '2'
      #garagedoorlock tamper
    - platform: state
      entity_id: !env_var GDAT
      state: '161'
      #backdoorlock burglar
    - platform: state
      entity_id: !env_var BDB
      state: '2'
      #backdoorlock tamper
    - platform: state
      entity_id: !env_var BDAT
      state: '161'
      #frontdoorlock burglar
    - platform: state
      entity_id: !env_var FDB
      state: '2'
      #frontdoorlock tamper
    - platform: state
      entity_id: !env_var FDAT
      state: '161'  
      #basementwindow sensor
    - platform: state
      entity_id: !env_var BASEMENTWINDOW
      from: 'off'
      to: 'on'
  condition:
      condition: state
      entity_id: alarm_control_panel.security_system
      state: 'armed_home'
  action:
    - service: notify.myiphone
      data:
        message: "Alarm Tripped!"
#      data_template:
#        message: >
#          Alarm tripped at {{ trigger.to_state.name }}!
        data:
          push:
            badge: 0
            category: "ALARM"
