#garage    
- alias: Close garage opener after set time
  trigger:  
    platform: state
    entity_id: garage_door.garage_opener
    state: 'open'
  condition:
    condition: state
    entity_id: input_boolean.garageopener_timer
    state: 'on'
  action:
    service: script.timed_garageopener

- alias: Disable garage opener timer
  trigger:  
    platform: state
    entity_id: input_boolean.garageopener_timer
    state: 'off'
  condition: use_trigger_values
  action:
    service: script.turn_off
    entity_id: script.garage_opener_timer

- alias: Re-enable garage opener timer
  trigger:  
    platform: state
    entity_id: input_boolean.garageopener_timer
    state: 'off'
    for:
      minutes: 30
  condition: use_trigger_values
  action:
    service: homeassistant.turn_on
    data:
        entity_id: input_boolean.garageopener_timer
