#garage notify
- alias: Notify garage open
  trigger:
    - platform: state
      entity_id: !env_var MYQDOOR
      state: 'open'
  action:
    - service: notify.myiphone
      data:
        message: "Garage opened"
        data:
          push:
            badge: 0
            category: "ALARM"

- alias: Notify garage closed
  trigger:
    - platform: state
      entity_id: !env_var MYQDOOR
      state: 'closed'
  action:
    - service: notify.myiphone
      data:
        message: "Garage closed"

- alias: Notify garage open for time
  trigger:  
    - platform: state
      entity_id: !env_var MYQDOOR
      state: 'open'
      for:
        minutes: 5
    - platform: state
      entity_id: !env_var MYQDOOR
      state: 'open'
      for:
        minutes: 10
    - platform: state
      entity_id: !env_var MYQDOOR 
      state: 'open'
      for:
        minutes: 20
    - platform: state
      entity_id: !env_var MYQDOOR 
      state: 'open'
      for:
        minutes: 30  
  condition:
    condition: state
    entity_id: input_boolean.garageopener_timer
    state: 'on'
  action:
    - service: notify.myiphone
      data:
        message: "Garage was left open"
