#garage
- alias: Close garage opener after set time
  trigger:  
    platform: state
    entity_id: garage_door.garage_opener
    state: 'open'
  condition:
    condition: state
    entity_id: input_boolean.garageopener_timer
    state: 'on'
  action:
    service: script.timed_garageopener

- alias: Disable garage opener timer
  trigger:  
    platform: state
    entity_id: input_boolean.garageopener_timer
    state: 'off'
  condition: use_trigger_values
  action:
    service: script.turn_off
    entity_id: script.garage_opener_timer
    
- alias: Notify garage open
  trigger:  
    - platform: state
      entity_id: sensor.garageopener_status
      state: 'open'
      for:
        minutes: 5
    - platform: state
      entity_id: sensor.garageopener_status
      state: 'open'
      for:
        minutes: 10
    - platform: state
      entity_id: sensor.garageopener_status
      state: 'open'
      for:
        minutes: 20
    - platform: state
      entity_id: sensor.garageopener_status
      state: 'open'
      for:
        minutes: 30  
  condition:
    condition: state
    entity_id: input_boolean.garageopener_timer
    state: 'on'
  action:
    service: notify.googlevoice
    data:
        message: "Garage Door Was Left Open!"
        target: !env_var MYCELL
        
- alias: Re-enable garage opener timer
  trigger:  
    platform: state
    entity_id: input_boolean.garageopener_timer
    state: 'off'
    for:
      minutes: 30
  condition: use_trigger_values
  action:
    service: homeassistant.turn_on
    data:
        entity_id: input_boolean.garageopener_timer

#- alias: Garage opener detect car
#  trigger:
#    platform: state
#    entity_id: !env_var MYCAR
#    state: 'home'
#  condition:
#    condition: state
#    entity_id: input_boolean.garage_bt
#    state: 'on'
#  action:
#    service: garage_door.open
#    entity_id: garage_door.garage_opener
#
#- alias: Garage opener no detect car
#  trigger:
#    platform: state
#    entity_id: !env_var MYCAR
#    state: 'not_home'
#  condition:
#    condition: state
#    entity_id: input_boolean.garage_bt
#    state: 'on'
#  action:
#    service: garage_door.close
#    entity_id: garage_door.garage_opener
