#googletravel
- alias: "Commute to work by car"
  trigger:
    platform: numeric_state
    entity_id: sensor.google_travel_time_car
    below: 30
  condition:
    condition: time
    after: '7:30'
    before: '8:00'
  action:
    service: notify.googlevoice
    data:
      message: "Commute by car less than 30 minutes"
      target: !env_var MYCELL

- alias: "Commute to work by bike"
  trigger:
    platform: numeric_state
    entity_id: sensor.google_travel_time_bike
    below: 50
  condition:
    condition: time
    after: '6:15'
    before: '7:15'
  action:
    service: notify.googlevoice
    data:
      message: "Commute by bike less than 50 minutes"
      target: !env_var MYCELL
