#googletravel
- alias: "Commute to work by car"
  trigger:
    platform: numeric_state
    entity_id: sensor.google_travel_time_car
    above: 25
  condition:
      - condition: state
        entity_id: !env_var MYPHONE
        state: 'home'
      - condition: time
        after: '7:00:00'
        before: '8:30:00'
  action:
    service: notify.googlevoice
    data:
      target: !env_var MYCELL
      message: >
        Driving commute delay of {{ trigger_to_state|round }} minutes
        
- alias: "Commute from work by car"
  trigger:
    platform: numeric_state
    entity_id: sensor.google_travel_time_car_work
    above: 25
  condition:
      - condition: state
        entity_id: !env_var MYPHONE
        state: 'work'
      - condition: time
        after: '15:45:00'
        before: '16:45:00'
  action:
    service: notify.googlevoice
    data:
      target: !env_var MYCELL
      message: >
        Driving commute delay of {{ trigger_to_state|round }} minutes

- alias: "Commute to work by bike"
  trigger:
    platform: numeric_state
    entity_id: sensor.google_travel_time_bike
    above: 60
  condition:
      - condition: state
        entity_id: !env_var MYPHONE
        state: 'home'
      - condition: time
        after: '6:15:00'
        before: '7:15:00'
  action:
    service: notify.googlevoice
    data:
      target: !env_var MYCELL
      message: > 
        Biking commute of {{ trigger_to_state|round }} minutes
