- alias: iOS Event Sound Alarm
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SOUND_ALARM
  action:
    service: script.alarm_away

- alias: iOS Event Silence Alarm
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SILENCE_ALARM
  action:
    - service: script.all_clear
    - service: homeassistant.turn_off
      entity_id: input_boolean.panic_mode
