#switch_lights
- alias: Turn on mudroom when backdoor unlocked from keypad
  trigger:
    platform: state
    entity_id: !env_var BACKDOORLOCK
    state: 'unlocked'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.auto_light_timer
        state: 'on'
      - condition: state
        entity_id: !env_var BDAT
        state: '19'
      - condition: state
        entity_id: !env_var BDAC 
        state: '6'
  action:
    service: script.timed_mudroom

- alias: Turn on hallway when frontdoor unlocked from keypad
  trigger:
    platform: state
    entity_id: !env_var FRONTDOORLOCK
    state: 'unlocked'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.auto_light_timer
        state: 'on'
      - condition: state
        entity_id: !env_var FDAT
        state: '19'
      - condition: state
        entity_id: !env_var FDAC
        state: '6'
  action:
    service: script.timed_diningroom

- alias: Boudoir wakeup
  trigger:
    platform: time
    after: '06:45:00'
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
    service: scene.turn_on
    entity_id: scene.wakeup_boudoir

- alias: Turn on patio lights after sunset
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 0
  condition: use_trigger_values
  action:
    service: switch.turn_on
    entity_id: group.patio_lights
      
- alias: Turn off patio lights after sunrise
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 0
  condition: use_trigger_values
  action:
    service: switch.turn_off
    entity_id: group.patio_lights

- alias: Turn off all indoor lights
  trigger:
    platform: state
    entity_id: group.users
    state: 'not_home'
    for:
      minutes: 20
  condition: use_trigger_values
  action:
    service: homeassistant.turn_off
    entity_id: group.indoor_lights
