#switch_lights
- alias: Turn on laundryroom when backdoor unlocked from keypad
  trigger:
    platform: state
    entity_id: lock.back_door__2
    state: 'unlocked'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.back_door_access_control_2
        state: '6'
      - condition: state
        entity_id: sensor.back_door_alarm_type_2
        state: '19'
      - condition: sun
        after: sunset
        after_offset: '-4:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_laundryroom

- alias: Turn off all indoor lights
  trigger:
    platform: state
    entity_id: group.users
    state: 'not_home'
  condition: use_trigger_values
  action:
    service: switch.turn_off
    entity_id: group.indoor_lights
