#lock alarms
- alias: Front Door Lock Forced Entry
  trigger:
      - platform: state
        entity_id: !env_var FDB
        state: '2'
  condition: use_trigger_values
  action:
    service: script.fdburglar

- alias: Back Door Lock Forced Entry
  trigger:
      - platform: state
        entity_id: !env_var BDB
        state: '2'
  condition: use_trigger_values
  action:
    service: script.bdburglar

- alias: Gararage Door Lock Forced Entry
  trigger:
      - platform: state
        entity_id: !env_var GDB
        state: '2'
  condition: use_trigger_values
  action:
    service: script.gdburglar
    
- alias: Front Door Lock Keypad Tamper
  trigger:
      - platform: state
        entity_id: !env_var FDAC
        state: '16'
      - platform: state
         entity_id: !env_var FDAT
         state: '161'
  condition: use_trigger_values
  action:
    service: script.fdtamper

- alias: Front Door Lock Keypad Tamper
  trigger:
      - platform: state
        entity_id: !env_var BDAC
        state: '16'
      - platform: state
         entity_id: !env_var BDAT
         state: '161'
  condition: use_trigger_values
  action:
    service: script.bdtamper
    
- alias: Front Door Lock Keypad Tamper
  trigger:
      - platform: state
        entity_id: !env_var GDAC
        state: '16'
      - platform: state
         entity_id: !env_var GDAT
         state: '161'
  condition: use_trigger_values
  action:
    service: script.gdtamper
