- alias: Back Door Lock keypad unlocks Garage Door Lock
  trigger:
    platform: state
    entity_id: !env_var BDAT
    from: '22'
    to: '18'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.users
        state: home
      - condition: state
        entity_id: !env_var MYPHONE
        state: garage
      - condition: state
        entity_id: !env_var HERPHONE
        state: garage
  action:
    - service: script.timed_garage_lights
    - service: lock.unlock
      entity_id: !env_var GARAGEDOORLOCK
      
- alias: Garage Door Lock keypad unlocks Back Door Lock
  trigger:
    platform: state
    entity_id: !env_var GDAT
    from: '22'
    to: '18'
  action:
    - service: script.timed_mudroom
    - service: lock.unlock
      entity_id: !env_var BACKDOORLOCK
    - service: switch.turn_off
      entity_id: !env_var GARAGELIGHTS

