- alias: Morning locks
  trigger:
    platform: state
    entity_id: !env_var BACKDOORLOCK
    state: 'unlocked'
  condition:
    - condition: time
      after: '06:45:00'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: lock.unlock
    entity_id: !env_var GARAGEDOORLOCK
    
