- alias: Back Door Lock keypad unlocks Garage Door Lock
  trigger:
    platform: state
    entity_id: !env_var BDAT
    state: '18'
  condition: use_trigger_values
  action:
    - condition: template
      value_template: "{{ trigger.from_state.state != '18' }}"
    - service: lock.unlock
      entity_id: !env_var GARAGEDOORLOCK
      
- alias: Garage Door Lock keypad unlocks Back Door Lock
  trigger:
    platform: state
    entity_id: !env_var GDAT
    state: '18'
  condition: use_trigger_values
  action:
    - condition: template
      value_template: "{{ trigger.from_state.state != '18' }}"
    - service: lock.unlock
      entity_id: !env_var BACKDOORLOCK