- alias: Lock battery low alert
  trigger:
      - platform: numeric_state
        entity_id: sensor.front_door_batt
        below: 5
      - platform: numeric_state
        entity_id: sensor.back_door_batt
        below: 5
      - platform: numeric_state
        entity_id: sensor.garage_door_batt
        below: 5
  condition: use_trigger_values
  action:
    service: notify.googlevoice
    data_template:
      message: >
        Change the {{ trigger.entity_id.split('.')[1].replace('_batt', '').replace('_',' ') }} lock battery
      target: !env_var MYCELL
