#thermostat
- alias: Thermostat - Mode Home
  trigger:
    platform: state
    entity_id: sensor.weather_temperature
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: sensor.thermostat_away
      state: 'off'
    - condition: state
      entity_id: sensor.thermostat_mode
      state: 'home'
  action:
    service: script.turn_on
    data:
      entity_id: script.auto_thermo

- alias: Thermostat - Mode Sleep
  trigger:
    platform: state
    entity_id: sensor.weather_temperature
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: sensor.thermostat_away
      state: 'off'
    - condition: state
      entity_id: sensor.thermostat_mode
      state: 'sleep'
  action:
    service: script.turn_on
    data:
      entity_id: script.auto_thermo

- alias: Thermostat - Auto Home
  trigger:
    platform: state
    entity_id: group.users
    state: 'home'
  condition: use_trigger_values
  action:
    - service: thermostat.set_away_mode
      data:
        entity_id: thermostat.home
        away_mode: 'False'
    - service: input_select.select_option
      data:
        entity_id: input_select.thermo_away
        options: 'Off'

- alias: Thermostat - Auto Away
  trigger:
    platform: state
    entity_id: group.users
    state: 'not_home'
  condition: use_trigger_values
  action:
    - service: thermostat.set_away_mode
      data:
        entity_id: thermostat.home
        away_mode: 'True'
    - service: input_select.select_option
      data:
        entity_id: input_select.thermo_away
        option: 'On'
    - service: script.turn_off  
      data:
        entity_id: script.auto_thermo

- alias: Thermostat - Select HVAC Auto
  trigger:
    platform: state
    entity_id: input_select.thermo_hvac
    state: 'Auto'
  condition: use_trigger_values
  action:
    service: thermostat.set_hvac_mode
    data:
      entity_id: thermostat.home
      hvac_mode: 'auto'

- alias: Thermostat - Select HVAC Cool
  trigger:
    platform: state
    entity_id: input_select.thermo_hvac
    state: 'Cool'
  condition: use_trigger_values
  action:
    service: thermostat.set_hvac_mode
    data:
      entity_id: thermostat.home
      hvac_mode: 'cool'

- alias: Thermostat - Select HVAC Heat
  trigger:
    platform: state
    entity_id: input_select.thermo_hvac
    state: 'Heat'
  condition: use_trigger_values
  action:
    service: thermostat.set_hvac_mode
    data:
      entity_id: thermostat.home
      hvac_mode: 'heat'

- alias: Thermostat - Select HVAC Off
  trigger:
    platform: state
    entity_id: input_select.thermo_hvac
    state: 'Off'
  condition: use_trigger_values
  action:
    service: thermostat.set_hvac_mode
    data:
      entity_id: thermostat.home
      hvac_mode: 'off'

- alias: Thermostat - Select Away Off
  trigger:
    platform: state
    entity_id: input_select.thermo_away
    state: 'Off'
  condition: use_trigger_values
  action:
    service: thermostat.set_away_mode
    data:
      entity_id: thermostat.home
      away_mode: 'off'

- alias: Thermostat - Select Away On
  trigger:
    platform: state
    entity_id: input_select.thermo_away
    state: 'On'
  condition: use_trigger_values
  action:
    service: thermostat.set_away_mode
    data:
      entity_id: thermostat.home
      away_mode: 'on'

#- alias: Thermostat - Select low temp
#  trigger:
#    platform: state
#    entity_id: input_slider.thermo_low
#  condition: use_trigger_values
#  action:      
#    service: script.turn_on
#    data:
#      entity_id: script.thermo_slider_low 

#- alias: Thermostat - Select high temp
#  trigger:
#    platform: state
#    entity_id: input_slider.thermo_high
#  condition: use_trigger_values
#  action:
#    service: thermostat.set_target_temp_high
#    data:
#      entity_id: thermostat.home
#      target_temp_high: '{{ state.input_slider.thermo_high.state }}'
