#thermo home/away
- alias: Thermostat - Auto Home
  trigger:
    platform: state
    entity_id: group.users
    from: not_home
    to: home
  condition:
    condition: state
    entity_id: input_boolean.thermo_away
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.thermo_away

- alias: Thermostat - Auto Away
  trigger:
    platform: state
    entity_id: group.users
    state: 'not_home'
    for:
      hours: 3
  condition:
    condition: state
    entity_id: input_boolean.thermo_away
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.thermo_away

- alias: Thermostat - Away Input
  trigger:
    - platform: state
      entity_id: sensor.ecobee_away
      state: 'on'
    - platform: state
      entity_id: sensor.ecobee_away
      state: 'off'
  action:
    service_template: >
      {% if is_state('sensor.ecobee_away', 'off') %}
        homeassistant.turn_off
      {% elif is_state('sensor.ecobee_away', 'on') %}
        homeassistant.turn_on
      {% else %}
      {% endif %}
    entity_id: input_boolean.thermo_away
    
- alias: Thermostat - Input Away
  trigger:
    - platform: state
      entity_id: input_boolean.thermo_away
      state: 'on'
    - platform: state
      entity_id: input_boolean.thermo_away
      state: 'off'
  action:
    service: thermostat.set_away_mode
    entity_id: thermostat.ecobee
    data_template:
      away_mode: >
        {% if is_state('input_boolean.thermo_away', 'off') %}
          off
        {% elif is_state('input_boolean.thermo_away', 'on') %}
          on
        {% else %}
        {% endif %}
