#thermo home/away
- alias: Thermostat - Coming Home
  trigger:
    platform: numeric_state
    entity_id: proximity.home
    below: 5
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{% if is_state_attr('proximity.home', 'dir_of_travel', 'towards') %}true{% endif %}"
      - condition: state
        entity_id: input_boolean.thermo_away
        state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.thermo_away

- alias: Thermostat - Home
  trigger:
    platform: numeric_state
    entity_id: proximity.home
    below: 1
  condition:
    condition: state
    entity_id: input_boolean.thermo_away
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.thermo_away

- alias: Thermostat - Away
  trigger:
    platform: numeric_state
    entity_id: proximity.home
    above: 2
  condition:
    condition: state
    entity_id: input_boolean.thermo_away
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.thermo_away

- alias: Thermostat - Away Input
  trigger:
    - platform: state
      entity_id: sensor.ecobee_away
  action:
    service_template: >
      {% if is_state('sensor.ecobee_away', 'off') %}
        homeassistant.turn_off
      {% elif is_state('sensor.ecobee_away', 'on') %}
        homeassistant.turn_on
      {% else %}
      {% endif %}
    entity_id: input_boolean.thermo_away
    
- alias: Thermostat - Input Away
  trigger:
    - platform: state
      entity_id: input_boolean.thermo_away
  action:
    service: climate.set_away_mode
    entity_id: climate.ecobee
    data_template:
      away_mode: >
        {% if is_state('input_boolean.thermo_away', 'off') %}
          off
        {% elif is_state('input_boolean.thermo_away', 'on') %}
          on
        {% else %}
        {% endif %}
