#security
all_clear:
  alias: "All Clear"
  sequence:
    - service: homeassistant.turn_off
      entity_id: script.alarm_home
    - service: homeassistant.turn_off
      entity_id: script.alarm_away
    - service: switch.turn_off
      entity_id: !env_var SIREN
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.security_system
    - service: notify.myiphone
      data:
        message: "All Clear"
        data:
          push:
            badge: 0
            category: "ALARM"

alarm_away:
  alias: "Away Alarm Tripped"
  sequence:
    - service: switch.turn_on
      entity_id: !env_var SIREN
    - service: notify.myiphone
      data:
        message: "Siren Activated!"
        data:
          push:
            badge: 0
            category: "ALARM"

alarm_home:
  alias: "Away Alarm Tripped"
  sequence:
    - delay:
        minutes: 5
    - service: switch.turn_on
      entity_id: !env_var SIREN
    - service: notify.myiphone
      data:
        message: "Siren Activated!"
        data:
          push:
            badge: 0
            category: "ALARM"
