#security
all_clear:
  alias: "All Clear"
  sequence:
    - service: switch.turn_off
      entity_id: !env_var SIREN
    - service: homeassistant.turn_off
      entity_id: input_boolean.alarm_tripped
    - service: script.turn_off
      data:
        entity_id: script.alarm_tripped

alarm_tripped:
  alias: "Alarm Tripped"
  sequence:
    - service: notify.myiphone
      data:
        message: "Alarm Has Been Tripped!"
        data:
          push:
            badge: 0
            category: "ALARM"
    - service: homeassistant.turn_on
      entity_id: input_boolean.alarm_tripped
    - service: homeassistant.turn_on
      entity_id: input_boolean.panic_mode
