#speedtest
- platform: speedtest
  minute: 30
  hour:
    - 0
    - 3
    - 6
    - 9
    - 12
    - 15
    - 18
    - 21
    - 24
  monitored_conditions:
    - ping
    - download
    - upload
  warnings: off
