#thermostat
- platform: template
  sensors:
    ecobee_mode:
      value_template: '{{ states.thermostat.ecobee.attributes.mode }}'
      warnings: off
    ecobee_away:
      value_template: '{{ states.thermostat.ecobee.attributes.away_mode }}'
      warnings: off
    ecobee_hvac:
      value_template: '{{ states.thermostat.ecobee.attributes.hvac_mode }}'
      warnings: off
    ecobee_target_temp_low:
      value_template: '{{ states.thermostat.ecobee.attributes.target_temp_low }}'
      warnings: off
    ecobee_target_temp_high:
      value_template: '{{ states.thermostat.ecobee.attributes.target_temp_high }}'
      warnings: off
