#thermostat
- platform: template
  sensors:
    thermostat_mode:
      value_template: '{{ states.thermostat.home.attributes.mode }}'

- platform: template
  sensors:
    thermostat_away:
      value_template: '{{ states.thermostat.home.attributes.away_mode }}'

- platform: template
  sensors:
    thermostat_hvac:
      value_template: '{{ states.thermostat.home.attributes.hvac_mode }}'

- platform: template
  sensors:
    thermostat_target_temp_low:
      value_template: '{{ states.thermostat.home.attributes.target_temp_low }}'

- platform: template
  sensors:
    thermostat_target_temp_high:
      value_template: '{{ states.thermostat.home.attributes.target_temp_high }}'
